# Generated by Django 4.2.2 on 2023-06-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='mission',
            field=models.TextField(default='To enable people and businesses throughout the world to realize their full potential.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='objectives',
            field=models.TextField(default='Deep understanding of system integration testing (SIT) and user acceptance testing (UAT).'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='vision',
            field=models.TextField(default='To be a successful global information technology company trusted by its customers for service excellence.'),
        ),
    ]
